version: '3'

services:

  server:
    image: nestjs-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm start
    environment:
      NODE_ENV: development
      HOST: "0.0.0.0"
      PORT: 3000
      POSTGRES_URL: postgres://postgres:password@postgres/postgres
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TEST_USER
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data: